In [292]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline
import plotly
import cufflinks as cf
import plotly.express as px
cf.go_offline()

Areas = pd.read_csv('Areas.csv', sep='\t')
Current = pd.read_csv('Current_Data.csv', sep='\t')
Items = pd.read_csv('Items.csv', sep='\t')
Periods = pd.read_csv('Period_Names.csv', sep='\t')
Series = pd.read_csv('Series.csv', sep='\t')

# I cleaned the data and made the appropriate merges (there is WHITESPACE ** Make Sure To Clean Whitespace) **

complete_df = pd.merge(Series, Areas, on='area_code').merge(Current, on='series_id        ').merge(Items, on='item_code').merge(Periods, on='period')
complete_df = complete_df.rename(columns = {'series_id        ': 'series_id', '       value': 'value'})
complete_df['series_id'] = complete_df['series_id'].str.strip()
complete_df['value'] = complete_df['value'].str.strip()

# Dropping the appropriate columns

complete_df.drop(['period_name', 'footnote_codes_x', 'footnote_codes_y', 'series_title', 'series_id', 'area_code', 'period', 'begin_year', 'begin_period', 'end_year', 'end_period'], axis=1, inplace=True)

# Dropping certain 'value' rows containing the hyphen (-) as filler

condition = complete_df[complete_df['value'] == '-'].index
complete_df.drop(condition, axis=0, inplace=True)

# Changing Certain Data Types from Strings to Float, Int, or DateTime

complete_df['value'] = complete_df['value'].astype(float)

# Table Transformations / Sorting

months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
complete_df.set_index('year', inplace=True)

# Changing Parentheses to another character due to regex

complete_df['item_name'] = complete_df['item_name'].str.replace('(', '').str.replace(')', '')

#Complete DF

complete_df

,item_code,area_name,value,item_name,period_abbr
year,,,,,
1995,701111,U.S. city average,0.238,"Flour, white, all purpose, per lb. 453.6 gm",JAN
1996,701111,U.S. city average,0.262,"Flour, white, all purpose, per lb. 453.6 gm",JAN
1997,701111,U.S. city average,0.309,"Flour, white, all purpose, per lb. 453.6 gm",JAN
1998,701111,U.S. city average,0.299,"Flour, white, all purpose, per lb. 453.6 gm",JAN
1999,701111,U.S. city average,0.297,"Flour, white, all purpose, per lb. 453.6 gm",JAN
...,...,...,...,...,...
2020,FS1101,U.S. city average,3.533,"Butter, stick, per lb. 453.6 gm",DEC
2021,FS1101,U.S. city average,3.474,"Butter, stick, per lb. 453.6 gm",DEC
2021,FS1101,West,3.772,"Butter, stick, per lb. 453.6 gm",DEC
1995,703611,Northeast,3.315,"Steak, sirloin, USDA Choice, bone-in, per lb. ...",DEC
1996,703611,Northeast,3.127,"Steak, sirloin, USDA Choice, bone-in, per lb. ...",DEC

In [375]:
# Function that takes in an item_code, and outputs the change in price of that item over a given interval

def getCategoryByCode(item_code=None):
    item_code = input()
    byItemCode = pd.DataFrame(complete_df.groupby(['year', 'item_code', 'item_name']).value.mean()).reset_index()
    if item_code in byItemCode['item_code'].values:
        category = byItemCode[byItemCode['item_code'] == item_code]
        lineplot = px.line(category, x='year', y='value', title=category['item_name'].unique()[0] + " Prices")
        return lineplot
    else:
        print('Sorry, that item code could not be located.')

# Function that takes in item_name as a query, narrows down the search to a finite list, and allows user to go in-depth

def getCategoryByName(item_name=None):
    item_name = input()
    print('NOTE: Use all Capital Letters for the query')
    byItemName = pd.DataFrame(complete_df.groupby(['year', 'item_name']).value.mean()).reset_index()
    byItemName['item_name'] = byItemName['item_name'].apply(lambda x: x.upper())
    filtered = byItemName[byItemName['item_name'].str.contains(item_name)]
    if filtered['item_name'].nunique() > 1:
        print('Insert a more specific query, as there is more than one result')
        print('Here is a list of the unique values related to your query: ' + str(list(filtered['item_name'].unique())))
    elif filtered['item_name'].nunique() == 0:
        print('This item either does not exist, please input an item that exists.')
    else:
        lineplot = px.line(filtered, x='year', y='value', title=filtered['item_name'].unique()[0] + " Prices")
        return lineplot

In [376]:
getCategoryByName()

 EGGS

NOTE: Use all Capital Letters for the query
Insert a more specific query, as there is more than one result
Here is a list of the unique values related to your query: ['EGGS, GRADE A, LARGE, PER DOZ.', 'EGGS, GRADE AA, LARGE, PER DOZ.']